"""empty message

Revision ID: 22b3cf3ac810
Revises: baeb61dfcbfc
Create Date: 2023-09-20 16:33:57.752457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b3cf3ac810'
down_revision = 'baeb61dfcbfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_bestplanet_uid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['bestplanet_uid'], ['uid'])

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=False))
        batch_op.drop_column('planet_uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_uid', sa.INTEGER(), server_default=sa.text("nextval('planet_planet_uid_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.drop_column('uid')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_bestplanet_uid_fkey', 'planet', ['bestplanet_uid'], ['planet_uid'])

    # ### end Alembic commands ###
