"""empty message

Revision ID: baeb61dfcbfc
Revises: 250855e213c8
Create Date: 2023-08-28 18:59:46.045570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baeb61dfcbfc'
down_revision = '250855e213c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('homeworld', sa.String(length=250), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('planet',
    sa.Column('planet_uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('planet_uid')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bestcharacter_uid', sa.Integer(), nullable=True),
    sa.Column('bestplanet_uid', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bestcharacter_uid'], ['characters.uid'], ),
    sa.ForeignKeyConstraint(['bestplanet_uid'], ['planet.planet_uid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('planet')
    op.drop_table('characters')
    # ### end Alembic commands ###
